### ISSUE TITLE
 has no exported member 'admin'

### ISSUE THREAD

**Issue by gperdomor** [Aginix/nestjs-firebase-admin#315]
Im trying to build my app but I got this errors:
```
node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-authentication.service.d.ts:5:51 - error TS2694: Namespace '"/src/node_modules/firebase-admin/lib/auth/index"' has no exported member 'admin'.

5     get auth(): import("firebase-admin/lib/auth").admin.auth.Auth;
                                                    ~~~~~

node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-database.service.d.ts:4:14 - error TS2416: Property 'app' in type 'FirebaseDatabaseService' is not assignable to the same property in base type 'Database'.
  Property 'automaticDataCollectionEnabled' is missing in type 'App' but required in type 'FirebaseApp'.

4     readonly app: admin.app.App;
               ~~~

  node_modules/@firebase/app-types/index.d.ts:50:3
    50   automaticDataCollectionEnabled: boolean;
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'automaticDataCollectionEnabled' is declared here.

node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-database.service.d.ts:6:59 - error TS2694: Namespace '"/src/node_modules/firebase-admin/lib/database/index"' has no exported member 'admin'.

6     get database(): import("firebase-admin/lib/database").admin.database.Database;
                                                            ~~~~~

node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-firestore.service.d.ts:2:22 - error TS2720: Class 'FirebaseFirestoreService' incorrectly implements class 'Firestore'. Did you mean to extend 'Firestore' and inherit its members as a subclass?
  Property 'bundle' is missing in type 'FirebaseFirestoreService' but required in type 'Firestore'.

2 export declare class FirebaseFirestoreService implements FirebaseFirestore.Firestore {
                       ~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@google-cloud/firestore/types/firestore.d.ts:319:5
    319     bundle(bundleId?: string): BundleBuilder;
            ~~~~~~
    'bundle' is declared here.

node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-messaging.service.d.ts:5:61 - error TS2694: Namespace '"/src/node_modules/firebase-admin/lib/messaging/index"' has no exported member 'admin'.

5     get messaging(): import("firebase-admin/lib/messaging").admin.messaging.Messaging;
                                                              ~~~~~

node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-remote-config.service.d.ts:5:68 - error TS2694: Namespace '"/src/node_modules/firebase-admin/lib/remote-config/index"' has no exported member 'admin'.

5     get remoteConfig(): import("firebase-admin/lib/remote-config").admin.remoteConfig.RemoteConfig;
                                                                     ~~~~~

node_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-storage.service.d.ts:6:57 - error TS2694: Namespace '"/src/node_modules/firebase-admin/lib/storage/index"' has no exported member 'admin'.

6     get storage(): import("firebase-admin/lib/storage").admin.storage.Storage;
                                                          ~~~~~

[4:28:50 PM] Found 7 errors. Watching for file changes.
```

**Comment by CodingAleCR** [comment]
I am also getting this error after updating firebase-admin to 9.4.2 and nestjs-firebase-admin to 2.0.2

**Comment by shahkeyur** [comment]
Is there any update here ?

**Comment by n3n** [comment]
@shahkeyur @CodingAleCR @gperdomor  Could you try `v2.1.0`?

**Comment by CodingAleCR** [comment]
Will do and get back to you ASAP. Thanks!
